services:
  - type: web
    name: price-search
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false
